[files]
extend-exclude = [
  "apps/desktop/bun.lock",
  "apps/desktop/src-tauri/Cargo.lock",
  "apps/desktop/src-sidecar/go.sum",
  "apps/desktop/src-tauri/icons/",
  "apps/desktop/node_modules/",
  "apps/desktop/src-tauri/target/",
]

[default.extend-words]
ot = "ot"
